server:
  port: 8081
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/swagger*"
      stat-view-servlet:
        login-username: gc
        login-password: gc
      validation-query: SELECT '1'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      pool-prepared-statements: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  #文件上传配置
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml,classpath:META-INF/modeler-mybatis-mappings/*.xml
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /efc01602.html
    tags-sorter: alpha
    operations-sorter: alpha
    version: 1.0
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '业务管理'
      paths-to-match: '/**'
      packages-to-scan: com.zh.controlcenter.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn